
"use client";

import { useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { MOCK_COMPANIES, getCoursesByCompany } from '@/data/mockDb';
import { useCompany } from '@/hooks/useCompany';
import { KanbanBoard } from '@/components/ui/KanbanBoard';
import { Plus, Wand2, X, Loader2, Sparkles } from 'lucide-react';
import { db } from '@/lib/firebase';
import { collection, addDoc, serverTimestamp } from 'firebase/firestore';

export default function CourseManagement() {
    const params = useParams();
    const router = useRouter();
    const domain = params.domain as string;
    const { company, loadingCompany } = useCompany(domain);
    const courses = company ? getCoursesByCompany(company.id) : [];
    
    // AI Builder State
    const [showAIModal, setShowAIModal] = useState(false);
    const [aiPrompt, setAIPrompt] = useState('');
    const [generating, setGenerating] = useState(false);

    const handleAIGenerate = async () => {
        if (!aiPrompt.trim() || !company) return;
        setGenerating(true);
        try {
            // Fake API latency
            await new Promise(resolve => setTimeout(resolve, 2000));
            
            const modulesToSave = [
                {
                    id: `m_${Date.now()}`,
                    title: `Introduction to ${aiPrompt}`,
                    lessons: [
                        { id: Date.now()+1, title: 'Welcome and Overview', type: 'video', videoUrl: 'https://youtube.com/watch?v=123', description: 'Generated by AI' },
                        { id: Date.now()+2, title: 'Key Concepts', type: 'quiz', questions: [{ id: 1, type: 'multichoice', text: 'What is the most important concept?', options: ['A','B','C'], correctAnswer: 'A' }] }
                    ]
                },
                {
                    id: `m_${Date.now()+10}`,
                    title: `Advanced ${aiPrompt}`,
                    lessons: [
                        { id: Date.now()+3, title: 'Deep Dive', type: 'video', videoUrl: 'https://youtube.com/watch?v=456', description: 'Generated by AI' }
                    ]
                }
            ];

            const courseData = {
                title: `${aiPrompt} (AI Generated)`,
                description: `A customized AI-generated course about ${aiPrompt}.`,
                domain,
                companyId: company.id,
                companyName: company.name,
                modules: modulesToSave,
                status: 'AVAILABLE',
                createdAt: serverTimestamp()
            };

            await addDoc(collection(db, 'courses'), courseData);
            setShowAIModal(false);
            setAIPrompt('');
            router.refresh(); // Or window.location.reload()
            window.location.reload();
        } catch (err) {
            console.error('AI Generation Error:', err);
            alert('Failed to generate course. Try again later.');
        } finally {
            setGenerating(false);
        }
    };

    if (loadingCompany) {
        return <div style={{ padding: '40px', textAlign: 'center' }}>Loading courses...</div>;
    }

    // Build Kanban data dynamically
    const items: Record<string, { id: string; content: string }> = {};
    const columnAvailable: string[] = [];
    const columnAssigned: string[] = [];
    const columnArchived: string[] = [];

    courses.forEach(course => {
        items[course.id] = { id: course.id, content: course.title };
        if (course.status === 'AVAILABLE') columnAvailable.push(course.id);
        else if (course.status === 'ASSIGNED') columnAssigned.push(course.id);
        else columnArchived.push(course.id);
    });

    const columns = {
        available: { id: 'available', title: '📂 Available Courses', itemIds: columnAvailable },
        assigned: { id: 'assigned', title: '✅ Assigned Courses', itemIds: columnAssigned },
        archived: { id: 'archived', title: '📁 Archived Courses', itemIds: columnArchived },
    };

    return (
        <div>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '12px', flexWrap: 'wrap', gap: '12px' }}>
                <div>
                    <h1 style={{ fontSize: '1.8rem', marginBottom: '4px' }}>Course Management</h1>
                    <p style={{ color: 'var(--text-muted)' }}>Drag courses between columns to assign or archive them.</p>
                </div>
                <div style={{ display: 'flex', gap: '12px' }}>
                    {company?.features?.includes('ai_builder') && (
                        <button onClick={() => setShowAIModal(true)} className="btn-secondary" style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '10px 18px' }}>
                            <Wand2 size={16} /> AI Course Builder
                        </button>
                    )}
                    <button className="btn-primary" style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '10px 18px', background: 'var(--tenant-primary, var(--primary))' }} onClick={() => router.push(`/company/${domain}/admin/courses/create`)}>
                        <Plus size={16} /> Create Course
                    </button>
                </div>
            </div>

            {/* Stats */}
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '16px', marginBottom: '24px' }}>
                <div className="card" style={{ borderLeft: `4px solid var(--tenant-primary, var(--primary))`, padding: '16px 20px' }}>
                    <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginBottom: '2px' }}>Available</div>
                    <div style={{ fontSize: '1.5rem', fontWeight: 700 }}>{columnAvailable.length}</div>
                </div>
                <div className="card" style={{ borderLeft: '4px solid #10b981', padding: '16px 20px' }}>
                    <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginBottom: '2px' }}>Assigned</div>
                    <div style={{ fontSize: '1.5rem', fontWeight: 700 }}>{columnAssigned.length}</div>
                </div>
                <div className="card" style={{ borderLeft: '4px solid #94a3b8', padding: '16px 20px' }}>
                    <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginBottom: '2px' }}>Archived</div>
                    <div style={{ fontSize: '1.5rem', fontWeight: 700 }}>{columnArchived.length}</div>
                </div>
            </div>

            {/* Kanban */}
            <div className="card">
                <KanbanBoard initialColumns={columns} items={items} />
            </div>

            {/* AI Modal */}
            {showAIModal && (
                <div style={{ position: 'fixed', inset: 0, zIndex: 999, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <div onClick={() => !generating && setShowAIModal(false)} style={{ position: 'absolute', inset: 0, background: 'rgba(0,0,0,0.5)', backdropFilter: 'blur(4px)' }} />
                    <div style={{ background: 'var(--surface)', borderRadius: '16px', padding: '32px', width: '90%', maxWidth: '500px', position: 'relative', zIndex: 1000, boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)' }}>
                        <button onClick={() => !generating && setShowAIModal(false)} style={{ position: 'absolute', top: '16px', right: '16px', background: 'none', border: 'none', cursor: 'pointer', opacity: 0.6 }}>
                            <X size={20} />
                        </button>
                        
                        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '8px' }}>
                            <div style={{ width: '40px', height: '40px', borderRadius: '10px', background: 'linear-gradient(135deg, #8b5cf6, #4f46e5)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'white' }}>
                                <Sparkles size={20} />
                            </div>
                            <h2 style={{ fontSize: '1.4rem', fontWeight: 700 }}>AI Course Builder</h2>
                        </div>
                        <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', marginBottom: '24px' }}>Describe the topic you want to teach, and AI will generate a complete course structure including modules and quizzes.</p>
                        
                        <textarea 
                            value={aiPrompt}
                            onChange={(e) => setAIPrompt(e.target.value)}
                            placeholder="e.g. A comprehensive guide to mastering digital marketing for beginners..."
                            style={{ 
                                width: '100%', padding: '16px', borderRadius: '12px', border: '1px solid var(--border)', 
                                background: 'var(--background)', fontSize: '0.95rem', minHeight: '120px', resize: 'vertical',
                                outline: 'none', marginBottom: '24px'
                            }}
                            disabled={generating}
                        />

                        <button 
                            onClick={handleAIGenerate}
                            disabled={generating || !aiPrompt.trim()}
                            style={{ 
                                width: '100%', padding: '14px', borderRadius: '12px', background: 'linear-gradient(135deg, #8b5cf6, #4f46e5)', 
                                color: 'white', fontWeight: 600, fontSize: '1rem', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '10px',
                                cursor: generating || !aiPrompt.trim() ? 'not-allowed' : 'pointer', opacity: generating || !aiPrompt.trim() ? 0.7 : 1, border: 'none'
                            }}
                        >
                            {generating ? (
                                <><Loader2 size={18} className="animate-spin" /> Generating Course...</>
                            ) : (
                                <><Wand2 size={18} /> Generate Course with AI</>
                            )}
                        </button>
                    </div>
                </div>
            )}
        </div>
    );
}
